//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VagabondEntities : DbContext
    {
        public VagabondEntities()
            : base("name=VagabondEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorsBG> AuthorsBGs { get; set; }
        public virtual DbSet<AuthorsEN> AuthorsENs { get; set; }
        public virtual DbSet<PicturesBG> PicturesBGs { get; set; }
        public virtual DbSet<PicturesEN> PicturesENs { get; set; }
    }
}
