//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicturesEN
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Technics { get; set; }
        public string Size { get; set; }
        public int Author { get; set; }
        public decimal Price { get; set; }
    
        public virtual AuthorsEN AuthorsEN { get; set; }
    }
}
