//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Id { get; set; }
        public string TitleBg { get; set; }
        public string TechnicsBg { get; set; }
        public string Size { get; set; }
        public int Author { get; set; }
        public decimal Price { get; set; }
        public bool IsSold { get; set; }
        public string PicturePath { get; set; }
        public string TitleEn { get; set; }
        public string TechnicsEn { get; set; }
    
        public virtual Author PicturesAuthor { get; set; }
    }
}
