//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAPI.ResourceEn", typeof(ResourceEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin panel.
        /// </summary>
        internal static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angel Angelov.
        /// </summary>
        internal static string angelAngelov {
            get {
                return ResourceManager.GetString("angelAngelov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lv.
        /// </summary>
        internal static string BgCurrency {
            get {
                return ResourceManager.GetString("BgCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is empty.
        /// </summary>
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eur.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product from card.
        /// </summary>
        internal static string deleteProductFromCart {
            get {
                return ResourceManager.GetString("deleteProductFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory.
        /// </summary>
        internal static string ErrorFieldsAreMandatory {
            get {
                return ResourceManager.GetString("ErrorFieldsAreMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory.
        /// </summary>
        internal static string ErrorMandatoryFields {
            get {
                return ResourceManager.GetString("ErrorMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundation.
        /// </summary>
        internal static string Foundation {
            get {
                return ResourceManager.GetString("Foundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content of home page.
        /// </summary>
        internal static string HomeContent {
            get {
                return ResourceManager.GetString("HomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle of home page.
        /// </summary>
        internal static string HomeSubtitle {
            get {
                return ResourceManager.GetString("HomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of home page.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about the shipment.
        /// </summary>
        internal static string InfoAboutTheShipment {
            get {
                return ResourceManager.GetString("InfoAboutTheShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        internal static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sold.
        /// </summary>
        internal static string IsSold {
            get {
                return ResourceManager.GetString("IsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added to the card.
        /// </summary>
        internal static string itemSuccessfullyPlacedInCart {
            get {
                return ResourceManager.GetString("itemSuccessfullyPlacedInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art center Vagabond.
        /// </summary>
        internal static string LogoVagabond {
            get {
                return ResourceManager.GetString("LogoVagabond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New product.
        /// </summary>
        internal static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on save.
        /// </summary>
        internal static string NewProductError {
            get {
                return ResourceManager.GetString("NewProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is saved successduly..
        /// </summary>
        internal static string NewProductSuccessfulSave {
            get {
                return ResourceManager.GetString("NewProductSuccessfulSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items in the shopping card.
        /// </summary>
        internal static string NoItemsInTheShoppingCart {
            get {
                return ResourceManager.GetString("NoItemsInTheShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered items:.
        /// </summary>
        internal static string OrderedItems {
            get {
                return ResourceManager.GetString("OrderedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order error.
        /// </summary>
        internal static string OrderError {
            get {
                return ResourceManager.GetString("OrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order form.
        /// </summary>
        internal static string OrderForm {
            get {
                return ResourceManager.GetString("OrderForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture does not exist.
        /// </summary>
        internal static string PictureDoesNotExist {
            get {
                return ResourceManager.GetString("PictureDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture name.
        /// </summary>
        internal static string PictureName {
            get {
                return ResourceManager.GetString("PictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string PicturesSubtitle {
            get {
                return ResourceManager.GetString("PicturesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string PicturesTitle {
            get {
                return ResourceManager.GetString("PicturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold out.
        /// </summary>
        internal static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technics.
        /// </summary>
        internal static string Technics {
            get {
                return ResourceManager.GetString("Technics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string totalPrice {
            get {
                return ResourceManager.GetString("totalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vagabond.
        /// </summary>
        internal static string Vagabond {
            get {
                return ResourceManager.GetString("Vagabond", resourceCulture);
            }
        }
    }
}
